extends Node2D


# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
func _ready():
	self.visible = false;

func set_text(text: String) -> void:
	$label.text = text
	

# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass


func _on_ESCItemWithTooltip_mouse_entered():
	self.visible = true # Replace with function body.
func _on_ESCItemWithTooltip_mouse_exited():
	self.visible = false # Replace with function body.
